In [81]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

# # File to Load 
school_data_loaded = r"C:\Users\Student\OneDrive\Desktop\module4 docs\Starter_Code\PyCitySchools\Resources\schools_complete.csv"
student_data_loaded = r"C:\Users\Student\OneDrive\Desktop\module4 docs\Starter_Code\PyCitySchools\Resources\students_complete.csv"


#  Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv(school_data_loaded)
# school_data.head()

student_data = pd.read_csv(student_data_loaded)

# Combine the data into a single dataset.
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])
school_data_complete.head(30)

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
7,7,Nicole Baker,F,12th,Huang High School,96,69,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635
10,10,Andrew Alexander,M,10th,Huang High School,90,70,0,District,2917,1910635
11,11,Daniel Cooper,M,10th,Huang High School,78,77,0,District,2917,1910635
12,12,Brittney Walker,F,9th,Huang High School,64,79,0,District,2917,1910635
13,13,William Long,M,9th,Huang High School,71,79,0,District,2917,1910635
14,14,Tammy Hebert,F,10th,Huang High School,85,67,0,District,2917,1910635
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88,0,District,2917,1910635
16,16,Donald Zamora,M,9th,Huang High School,88,55,0,District,2917,1910635
17,17,Kimberly Santiago,F,9th,Huang High School,74,75,0,District,2917,1910635
18,18,Kevin Stevens,M,9th,Huang High School,64,69,0,District,2917,1910635
19,19,Brandi Lyons,F,9th,Huang High School,89,80,0,District,2917,1910635
20,20,Lisa Davis,F,10th,Huang High School,91,89,0,District,2917,1910635
21,21,Kristen Lopez,F,10th,Huang High School,90,77,0,District,2917,1910635
22,22,Kimberly Stewart,F,11th,Huang High School,99,84,0,District,2917,1910635
23,23,Christopher Parker,M,9th,Huang High School,81,68,0,District,2917,1910635
24,24,Chelsea Griffith,F,11th,Huang High School,85,73,0,District,2917,1910635
25,25,Cesar Morris,M,9th,Huang High School,92,70,0,District,2917,1910635
26,26,Melanie Decker,F,9th,Huang High School,63,85,0,District,2917,1910635
27,27,Tracey Oconnor,F,10th,Huang High School,80,58,0,District,2917,1910635
28,28,Kelly James,F,11th,Huang High School,73,55,0,District,2917,1910635
29,29,Nicole Brown,F,12th,Huang High School,90,88,0,District,2917,1910635

In [82]:
# Calculate the total number of unique schools
school_count =school_data_complete['School ID'].nunique()
school_count

15

In [83]:
# Calculate the total number of students
student_count =school_data_complete['Student ID'].nunique()
student_count

39170

In [84]:
# Calculate the total budget
total_budget =school_data_complete['budget'].sum()
print("Total Budget:", total_budget)

Total Budget: 82932329558

In [85]:
# Calculate the average (mean) math score
average_math_score =school_data_complete['math_score'].mean()
print("Average Math Score:", average_math_score)

Average Math Score: 78.98537145774827

In [86]:
# Calculate the average (mean) reading score
average_reading_score =school_data_complete['reading_score'].mean()
print("Average Reading Score:", average_reading_score)

Average Reading Score: 81.87784018381414

In [87]:
# Use the following to calculate the percentage of students who passed math (math scores greather than or equal to 70)
passing_math_count = school_data_complete[(school_data_complete["math_score"] >= 70)].count()["student_name"]
passing_math_percentage = passing_math_count / float(student_count) * 100
passing_math_percentage

74.9808526933878

In [88]:
passing_reading_count =school_data_complete[(school_data_complete["reading_score"] >= 70)].count()["student_name"]
passing_reading_percentage =passing_reading_count / float(student_count) * 100
passing_reading_percentage

85.80546336482001

In [89]:
passing_math_reading_count = school_data_complete[
    (school_data_complete["math_score"] >= 70) & (school_data_complete["reading_score"] >= 70)
].count()["student_name"]
overall_passing_rate = passing_math_reading_count /  float(student_count) * 100
overall_passing_rate

65.17232575950983

In [111]:
# district_summary = {}
data = {
'Total Schools': [school_count],
    'Total Students': [student_count],
    'Total Budget': [total_budget],
    'Average Math Score': [average_math_score],
    'Average Reading Score': [average_reading_score],
    '% Passing Math': [passing_math_percentage],
    '% Passing Reading': [passing_reading_percentage],
    '% Overall Passing': [overall_passing_rate]
}
district_summary = pd.DataFrame(data)
print(district_summary)

   Total Schools  Total Students  Total Budget  Average Math Score  \
0             15           39170   82932329558           78.985371

   Average Reading Score  % Passing Math  % Passing Reading  % Overall Passing
0               81.87784       74.980853          85.805463          65.172326

In [112]:
# Use the code provided to select the type per school from school_data
school_types = school_data.set_index(["school_name"])["type"]

In [ ]:
# Calculate the total student count per school from school_data
per_school_counts =

In [ ]:
# Calculate the total school budget and per capita spending per school from school_data
per_school_budget =
per_school_capita =

In [ ]:
# Calculate the average test scores per school from school_data_complete
per_school_math =
per_school_reading =

In [ ]:
# Calculate the number of students per school with math scores of 70 or higher from school_data_complete
students_passing_math =
school_students_passing_math =